apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-d
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nanavproject2
        image: nanav01/august4
        ports:
        - containerPort: 80
