apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: NodePort
  selector:
     app: nginx
  ports:
  - port: 80          # Port exposed within the cluster
    targetPort: 80  # Port on the pods
    nodePort: 30007   # Port accessible externally on each node

